version: '3'
services:
  app:
    build:
      context: .
      target: prod
    depends_on:
      - db

  db:
     image: mongo:7.0.0
   
  nginx:
    build: ./nginx
    ports:
      - '80:80'
      - '443:443' 
