version: '3'
services:
  app:
    build:
      context: .
      target: dev
    ports:
      - '8080:8080'
    depends_on:
      - db
    volumes:
      - ./:/root

  db:
     image: mongo:7.0.0
   
 
